language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
cache: bundler
sudo: false
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - Gemfile
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.2.gemfile
  - gemfiles/rails-5.0.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/rails-master.gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails-master.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails-master.gemfile
  allow_failures:
    - gemfile: gemfiles/rails-master.gemfile
  fast_finish: true
